Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["development.local"]
  config.vm.synced_folder "app","/app"
# sync a synced_folder
  #to_sync_folder, # to_sync_on_vm
  config.vm.synced_folder "app", "/app"
  #provisioning
  config.vm.provision "shell", path: "environment/provision.sh"

end
